### ISSUE TITLE
Fail to launch composite ui on Android release variant

### ISSUE THREAD

**Issue by stephenongunsw** [Azure-Samples/communication-services-ui-library-react-native#21]
### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
On Android, on Release variants
`yarn android --variant=release`

With avatar selected.

### Any log messages given by the failure
>
Alert popup with the message 'Error', 'no protocol: images_fox`

### Expected/desired behavior
>
No error with the composite UI shown.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Android only

### Versions
>
current master

### Mention any other details that might be useful
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/52565394/217111245-26c2c890-c490-460f-9519-e11f20e10f77.png)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Mohtasim** [comment]
Hi @stephenongunsw 
Thanks for registering this issue. We tested both Android and iOS. Seems like the issue is persistent in both platform. We will update here with the fix.

**Comment by stephenongunsw** [comment]
Thank you @Mohtasim. Any reason this branch is not yet pulled into the `main` branch?
