### ISSUE TITLE
Is this repo can be used for the android for vedio calling

### ISSUE THREAD

**Issue by MrDanis** [Azure-Samples/communication-services-ui-library-react-native#39]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pavelprystinka** [comment]
Hello @MrDanis,
 
This repo is a sample of how react native application (Android and iOS) can use Azure Communication Services [Calling UI Library](https://docs.microsoft.com/en-us/azure/communication-services/concepts/ui-library/ui-library-overview?pivots=platform-mobile).
 
Azure Communication Services Calling UI Library does provide Video Calling ability to Android and iOS applications. Please see link above or [Readme in the repo](https://github.com/Azure-Samples/communication-services-ui-library-react-native) for more information and guidance.
 
Thank you.
