### ISSUE TITLE
How to use this library for 1-on-1 video calling

### ISSUE THREAD

**Issue by ajayn1986** [Azure-Samples/communication-services-ui-library-react-native#40]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
documentation issue or request

### Minimal steps to reproduce
Not able to find documents or sample to use library for 1-on-1 video calling

### Any log messages given by the failure
no

### Expected/desired behavior
1-on-1 video calling needs to be supported for library to be usable

### OS and Version?
NA

### Versions
Latest

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by codal-hkrishnani** [comment]
Here is documentation for 1:1 video call

https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-with-video-calling?pivots=platform-android

**Comment by Mohtasim** [comment]
Hi @ajayn1986, 
Thank you for your query. Please refer to the QuickStart for the UI Library [QuickStart](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/ui-library/get-started-composites?tabs=kotlin&pivots=platform-android) and look at "Set up a 1:N Outgoing Call and Incoming Call Push Notifications" for 1:1 calling setup.
 
Android and iOS versions supporting 1:1 calling: 1.8.0
 
Please reference sample bindings for [Android](https://github.com/Azure-Samples/communication-services-ui-library-react-native/blob/main/demo/android/app/src/main/java/com/demo/RNAzureCommunicationUICalling.java) and [iOS](https://github.com/Azure-Samples/communication-services-ui-library-react-native/blob/main/demo/ios/RNAzureCommunicationUICalling.swift) to explore utilizing APIs from native UI Libraries.

Thank you :)

**Comment by ajayn1986** [comment]
Hi @Mohtasim, I believe the sample you have referred above isn't for react native library. Does it mean that we don't have this feature implemented in react native library yet?

**Comment by iaulakh** [comment]
Hi @ajayn1986 ,

The current React Native sample only supports outgoing calls. To add support for receiving incoming call notifications, please refer to the QuickStart guide for the UI Library [QuickStart](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/ui-library/get-started-composites?tabs=kotlin&pivots=platform-android). Specifically, look at the section "Set up a 1:N Outgoing Call and Incoming Call Push Notifications" for 1:1 calling setup.

To further explore utilizing APIs from native UI libraries, you can leverage the bindings for both [Android](https://github.com/Azure-Samples/communication-services-ui-library-react-native/blob/main/demo/android/app/src/main/java/com/demo/RNAzureCommunicationUICalling.java) and [iOS](https://github.com/Azure-Samples/communication-services-ui-library-react-native/blob/main/demo/ios/RNAzureCommunicationUICalling.swift).
