### ISSUE TITLE
Unable to join the room call from the android using react-native on windows

### ISSUE THREAD

**Issue by MrDanis** [Azure-Samples/communication-services-ui-library-react-native#44]
> **Unable to join the call due to error** 
this is the issue I face when i try to join the room call using  my ACS token 
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Mohtasim** [comment]
Hi @MrDanis, 
Thank you for reaching out regarding the issue. Could you share more information about this issue on the following questions?

* Did you try to join with correct room id?
* Was the ACS token generated for the user who is added to the room? 

Please see more on how to create room and [add users on the room](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/rooms/get-started-rooms?tabs=windows&pivots=programming-language-javascript#add-or-update-participants).

**Comment by MrDanis** [comment]
Hi @Mohtasim 
thanks for your response I have resolve this now I am able to call from one end to other end.
But I have one question to ask can you please tell me how can I get the ACSID of my user before or after initializing  the call fron now have add manually but in order to make it work properly we need to have the ACSID of the user before the start of call composite

**Comment by Mohtasim** [comment]
Hi @MrDanis,
Please see this article: [Quickstart: Create and manage access tokens](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/identity/access-tokens?tabs=windows&pivots=platform-azportal)
 
Depending on what platform you use create user token, you can see an `identity/id/userId/communicationUserId` is returned alongside of the user token.

**Comment by MrDanis** [comment]
Hi @Mohtasim 
Can you tell me how can we read the logs of file RNAzureCommunicationUICalling.java as we are using it for react-native can you please tell how to read the logs of that file.

**Comment by Mohtasim** [comment]
Hi @MrDanis,
You can read the logs of file `RNAzureCommunicationUICalling.java` as you are using React-Native application by looking at the [logcat section of Android Studio](https://developer.android.com/studio/debug/logcat). Primary steps are given below:
- Open the demo/andriod with Android Studio
- Do gradle sync and build
- Run your application
- Open logcat and filer by TAG to see your logs

There are other ways to see your logs as well. You can see logs from your [cli too](https://developer.android.com/tools/logcat).

**Comment by MrDanis** [comment]
thanks dear

**Comment by MrDanis** [comment]
@Mohtasim I have a question to ask 
Q) This project is build with minsdk : 26 and compile or targert sdk version is 33. So is there any way to use it with the app who is build on minsdk 21 and target or compile SDK version is 31?

**Comment by Mohtasim** [comment]
Hi @MrDanis, 
The dependent `communication-ui-library-calling` has min SDK as 26. So minSDK has to be 26 otherwise you might face audio or other issues. For compileSDK version, you can set it up to 34 so yes, you can set to 31.

**Comment by MrDanis** [comment]
Hi @Mohtasim  is this a must to have the react-native verion 0.72.14 along with the minsdk 26 to make this library work fine. As i have my react-native app with version of 0.68.2 so do i need to upgrade it to the 0.72.14 ?
