### ISSUE TITLE
Hi @Mohtasim i am trying to build an video call app all things are fine and working i would like to know that can you tell me that which code is responsible for the Join Call button

### ISSUE THREAD

**Issue by MrDanis** [Azure-Samples/communication-services-ui-library-react-native#49]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Mohtasim** [comment]
Hi [@MrDanis](https://github.com/MrDanis),
The React-Native sample uses UI Calling Library which is itself a composite experience meaning a single piece library (The setup where you see the join call button & Calling page where you interact with people in a call altogether). It does not offer API's component wise yet i.e. Join Call API as the underlaying implication and implementation is handled by the library to make life easier for the user devs. The Join Call button is part of the composite which triggers to join the call by call agent for the user.
If you look at the Native Bridging implementation, we have launch methods to launch the calling composite experience. This sample simply shows how you can utilize our UI Calling Library for Android & iOS in cross platform React-Native framework. The implementation for both Android & iOS after Native Bridging is -
* Android - https://github.com/Azure-Samples/communication-services-ui-library-react-native/blob/main/demo/android/app/src/main/java/com/demo/RNAzureCommunicationUICalling.java
* iOS - https://github.com/Azure-Samples/communication-services-ui-library-react-native/blob/main/demo/ios/RNAzureCommunicationUICalling.swift

However our `communication-ui-library-android` and `communication-ui-library-ios` are open source. The Android & iOS UI Calling Library itself is as below -
* Android - https://github.com/Azure/communication-ui-library-android
* iOS - https://github.com/Azure/communication-ui-library-ios

The join call click event implementation could be found and debugged from here below -
* Android - https://github.com/Azure/communication-ui-library-android/blob/main/azure-communication-ui/calling/src/main/java/com/azure/android/communication/ui/calling/presentation/fragment/setup/components/JoinCallButtonHolderView.kt
* iOS - https://github.com/Azure/communication-ui-library-ios/blob/main/AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupView.swift

May I also ask what would you like to achieve with the JoinCall button action override API? Perhaps, we could point you towards the right direction.

Hope this answered your question.
Thank you.

**Comment by Mohtasim** [comment]
Thanks @MrDanis. 
The screen with the `Join Call` button is referred as the `Setup Screen` as we use that screen to setup call configuration. We have a APIs to skip the setup screen and join the call directly. 
For Skip Setup Scree documentation if you need in future, please refer to this [page](https://learn.microsoft.com/en-us/azure/communication-services/how-tos/ui-library-sdk/skip-setup-screen?tabs=kotlin&pivots=platform-android)

Thanks :)
