### ISSUE TITLE
[bug] Failing to join video call on demo app due to callback issue

### ISSUE THREAD

**Issue by a-dubs** [Azure-Samples/communication-services-ui-library-react-native#50]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Clone repo, setup demo app per instructions provided by this repo
2. Build the app using Xcode 15.2 and run on iphone 14.
3. Once in the app, select "Room" mode and enter your token and room ID and press join, then once the call join dialogue appears where you can toggle mic and camera controls, press the join call button and then it should throw an error.

#### Snippet of error message:
> No callback found with cbID 25851 and callID 12925 for module <unknown>. Args: '[{"code":"callJoin","message":"Unknown
error","domain":"RCTErrorDomain","userinfo":null,"nati
veStackIOS":["0 React 0x0000000106a3660c
RCTJSErrorFromCodeMessageAnd NSError + 112","1 ..........

#### Full Screenshot of error:
<img src="https://github.com/user-attachments/assets/540274e0-2c80-43a7-925e-6aa13c3e00a0" width="400" />

### Expected/desired behavior
The video call should actually be able to start and not throw an error.

### OS and Version?
MacOS 14.5 Sanoma running Xcode 15.2. Using the most recent version of the repo (which uses v1.9.0 of AzureCommunicationUICalling sdk)

### Mention any other details that might be useful
This issue first occurred to me on a react native app that I have been developing. So, to sanity check myself, I tried building and running this demo app, but ran into the exact same error. 

---

Thank you in advance! I hope we can resolve this issue quickly :)

**Comment by pavelprystinka** [comment]
Hi @a-dubs,

Thank you for pointing out to this issue. It is not fixed in the main branch, you should be able to connect to the room.

**Comment by Lezoson** [comment]
Hi @pavelprystinka 

Still facing the same issue 

Thank you in advance
