### ISSUE TITLE
[docs] Links to java src files in android readme are dead links

### ISSUE THREAD

**Issue by a-dubs** [Azure-Samples/communication-services-ui-library-react-native#52]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Go to the android demo readme at [demo/android](https://github.com/Azure-Samples/communication-services-ui-library-react-native/tree/main/demo/android) and try clicking on any of the [RNAzureCommunicationUICalling.java](https://github.com/Azure-Samples/communication-services-ui-library-react-native/blob/main/demo/android/app/src/main/java/com/azurecommunicationuidemoapp/RNAzureCommunicationUICalling.java) or [RNAzureCommunicationUICallingPackage.java](https://github.com/Azure-Samples/communication-services-ui-library-react-native/blob/main/demo/android/app/src/main/java/com/azurecommunicationuidemoapp/RNAzureCommunicationUICallingPackage.java) hyperlinks and they will fail to take you to the appropriate files.

### Expected/desired behavior

`RNAzureCommunicationUICalling.java` links should take you to: https://github.com/Azure-Samples/communication-services-ui-library-react-native/blob/main/demo/android/app/src/main/java/com/demo/RNAzureCommunicationUICalling.java

`RNAzureCommunicationUICallingPackage.java` links should take you to: https://github.com/Azure-Samples/communication-services-ui-library-react-native/blob/main/demo/android/app/src/main/java/com/demo/RNAzureCommunicationUICallingPackage.java

**Comment by Mohtasim** [comment]
Thank you @a-dubs for bringing this up and for your contribution.

**Comment by a-dubs** [comment]
@Mohtasim happy to contribute!
