### ISSUE TITLE
Rooms Call not getting connected with Azure communication web app

### ISSUE THREAD

**Issue by Lezoson** [Azure-Samples/communication-services-ui-library-react-native#54]
Rooms call not getting connected with web call and mobile app

I have cloned and reproduced the latest Azure web calling hero and Azure communication react native mobile app but the call is not getting connected with each other, Whereas if i connect the call in mobile and then connect the web app its getting connected but if i do it in vice versa its not, hoping for the good solution

Thanks in advance.

**Comment by iaulakh** [comment]
Hi @Lezoson ,

Thank you for trying the UI Library samples. Regarding the issue, please share the following information:

- Are you using the same room ID on both devices? Is the ID created from the same ACS resource?
- Are you using different ACS access tokens on both devices? Each call participant requires an individual token.
- What are the roles of the room participants? [Rooms overview](https://learn.microsoft.com/en-us/azure/communication-services/concepts/rooms/room-concept). To test initially, you can try with the presenter role to test capabilities.

Please let me know if you need any further assistance.

**Comment by Lezoson** [comment]
Hi @iaulakh 

Iam using the room ID created from same resource and also if i use different access token the app is getting crashed and closes automatically but if i join with the access token i can able to join, Iam using presenter as the default role 

Kindly check on it and let me know it is same in your case

**Comment by Lezoson** [comment]
Hi @iaulakh 

Yes i created two different access token for two different devices to get connected with each other, but the participants are not connecting with each other in real time but i can able to hear the voice if i unmute my mic.

Now there is no crash in my app ie, because of the same access token 

Thank you.

**Comment by iaulakh** [comment]
Hi @Lezoson ,

Thank you for providing your feedback. Our Product Manager has sent you an email to schedule a session. Kindly respond to the email at your earliest convenience to discuss your concerns.

Thank you!

**Comment by pavelprystinka** [comment]
@Lezoson 
Closing this issue and continue conversation with product team.
