### ISSUE TITLE
For the M1 fix you can edit your podfile to set the config.buildsettings of the target

### ISSUE THREAD

**Issue by InquestApp-Admin** [Azure-Samples/communication-services-ui-library-react-native#6]
This is preferred to forcing to run on Rosette
Just change the post-install script to be 

  post_install do |installer|
    react_native_post_install(installer)
    # __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end

**Comment by JoshuaLai** [comment]
@InquestApp-Admin  Thanks for the suggestion we will be proposing this change into the underlying UI library. 
https://github.com/Azure/communication-ui-library-ios/pull/357

**Comment by JoshuaLai** [comment]
@InquestApp-Admin thanks for the suggestion: https://github.com/Azure-Samples/communication-services-ui-library-react-native/pull/10 PR has been merged in and this issues can be considered close. Please let us know if you run into any more issues.
