### ISSUE TITLE
Unable to Join Microsoft Teams Meeting After Adding Access Token and Teams Meeting Link in React Native Azure Communication Service

### ISSUE THREAD

**Issue by HarshalJ-SamarthT-24** [Azure-Samples/communication-services-ui-library-react-native#63]
**Expected/desired behavior:** 
The app should directly join the Microsoft Teams meeting after adding the access token and meeting link, without redirecting to an input fields screen.

**OS and Version:**
Windows 11 pro

**Versions:**
React Native: 0.72

**Mention any other details that might be useful:**
I have created an Azure Communication Services account and successfully generated the necessary user access token, identity, and endpoint. However, after inputting the access token and Microsoft Teams meeting link, clicking the "Launch" button and then "Join Call" redirects to an input fields page instead of joining the meeting. I am not sure whether this issue stems from the code or something within the Azure Communication Service setup. Could you please assist in identifying the cause of this issue and suggest how to resolve it?

**Comment by inancyGit** [comment]
Hi @HarshalJ-SamarthT-24 , we will get back with an update/response soon.

**Comment by inancyGit** [comment]
Hi @HarshalJ-SamarthT-24, it seems to work well with ACS Token. Request you to verify configuration with your code setup.

**Comment by HarshalJ-SamarthT-24** [comment]
> Hi @HarshalJ-SamarthT-24, it seems to work well with ACS Token. Request you to verify configuration with your code setup.

It’s not working well. I’ve set up an Azure Communication Services account, generated the user access token, identity, and endpoint successfully. However, after entering the access token and Teams meeting link, clicking "Launch" and "Join Call" redirects to an input fields page instead of joining the meeting. Could you help identify if the issue is with the code or the Azure setup?
