### ISSUE TITLE
Unable to Join Microsoft Teams Meeting After Adding Access Token and Teams Meeting Link in React Native Azure Communication Service

### ISSUE THREAD

**Issue by HarshalJ-SamarthT-24** [Azure-Samples/communication-services-ui-library-react-native#65]
Expected/desired behavior:
The app should directly join the Microsoft Teams meeting after adding the access token and meeting link, without redirecting to an input fields screen.

OS and Version:
Windows 11 pro

Versions:
React Native: 0.72

Mention any other details that might be useful:
I have created an Azure Communication Services account and successfully generated the necessary user access token, identity, and endpoint. However, after inputting the access token and Microsoft Teams meeting link, clicking the "Launch" button and then "Join Call" redirects to an input fields page instead of joining the meeting. I am not sure whether this issue stems from the code or something within the Azure Communication Service setup. Could you please assist in identifying the cause of this issue and suggest how to resolve it?

**Comment by inancyGit** [comment]
It doesnt seem to have a problem in code. This issue might be from ACS setup. Please check [Prerequisites](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/ui-library/get-started-composites?tabs=kotlin&pivots=platform-android)

**Comment by ShaunaSong** [comment]
Hello @HarshalJ-SamarthT-24:

Could you please provide more information?

Is this issue happening on the Android platform or iOS platform?
Are you using a physical device or trying it in an emulator?

Thanks

**Comment by HarshalJ-SamarthT-24** [comment]
Hello @ShaunaSong 
I have tried testing the issue on both an Android emulator and a physical device. I am working with Azure Communication Services for Microsoft Teams. I have provided a valid user access token and identity, which I generated from the Azure portal.

In the React Native app, when I input the Microsoft Teams meeting link, user access token, and identity into the text fields and press the "Launch" button, I then press "Start Call." I have already initiated the Teams meeting from the desktop using the link I provided, but when I press "Start Call," the meeting does not start from the React Native app.

This issue occurs consistently for me. Could you please provide a solution for this?

Thanks!

**Comment by ShaunaSong** [comment]
Hey @HarshalJ-SamarthT-24,

Thanks for the information. I tested it with our current codebase, and cannot reproduce your issue. 
Which type of Teams meeting were you trying to join—Teams for Work or Teams for Life?

Best,
Shauna

**Comment by HarshalJ-SamarthT-24** [comment]
@ShaunaSong 
I am using Teams for Work. Could you please share a screen recording showing how your Microsoft Teams meeting starts after adding the Microsoft Teams meeting link and Azure token in TextInput?

**Comment by HarshalJ-SamarthT-24** [comment]
@ShaunaSong 
I am using Teams for Work. Could you please share a screen recording showing how your Microsoft Teams meeting starts after adding the Microsoft Teams meeting link and Azure token in TextInput?
