### ISSUE TITLE
Add video and camera implementation

### ISSUE THREAD

**Issue by HeSingh93** [Azure-Samples/communication-services-ui-library-react-native#67]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

I've implemented the bridging and the .java file in my React Native project. But now when joining a call i cant see or use the built-in camera. I also cant see the participants camera in my meeting.

I noticed that the RNAzureCommunicationUICalling.java doesnt have anything with video in it, how do I implement it?

**Comment by ahammer** [comment]
Thank you for raising this issue with this sample project. Enabling the camera and remote video is a built-in feature of the Call Composite. To help us better understand the situation, could you please provide:

1) Screenshots or other details of what you’re observing.
2) Confirmation if you’ve granted camera permissions in your app.

Additionally, if you’re using the Audio-only mode of the Calling Composite, note that it disables both local and remote video feeds. Please ensure that this flag/option is not enabled.

Looking forward to your response to assist further.

Best regards,
   Adam Hammer

**Comment by ahammer** [comment]
Thank you for the update! It's great to hear that switching the enum to AUDIO_AND_VIDEO enabled video. To address the issue with the camera freezing, could you please:

- Share a screenshot of the Call Composite itself as it appears on the device experiencing the issue.
- Test the behavior on a second physical device and provide the device models and Android versions for both.
- Ensure the camera is not in use by another app while testing.
- Provide any relevant Logcat output after pressing the camera button to help identify why it may not be functioning.

This information will help us investigate the issue further. Let us know what you find!

**Comment by HeSingh93** [comment]
I noticed that it works on any other physical android device that I have. So I think its something with those specific devices. It is an android tablet with an integrated stand that has a camera that can be rotated.

**Comment by ahammer** [comment]
The issue appears to be related to the Rockchip RK3566 tablet’s camera configuration and potentially its Android system setup. The provided stack trace indicates that the device's camera cannot be resolved by the system, likely due to incompatibilities with the Camera2API or permission handling.
 
Our library is designed to support phones and tablets with standard front/back cameras. Devices with unconventional camera setups, like the Rockchip tablet you are using, may fall outside of our currently supported configurations.
 
We recommend using devices with standard camera configurations and established chipsets. If you can share the exact model details of the device, we can investigate acquiring for testing purposes.

**Comment by HeSingh93** [comment]
Its this model and type
https://www.uhopestar.com/sv/14inch-rk3566-large-memory-l-type-desktop-android-tablet-for-restaurant-ordering

The thing is that we also have a native kotlin app that uses the azure.android:azure-communication-calling package and with that package it manages to find and use the camera with the neccessary permissions.

But in that package we have other methods and models that can be used, for example the VideoDeviceInfo class, DeviceManager and DeviceProfile classes  etc.

I havent really found anything similar function in this package thats being implemented.

Is it possible to combine azure-communication-calling with this implementation?

**Comment by ahammer** [comment]
You are correct that the Azure Communication Calling SDK for Android offers a broader range of capabilities, including classes like VideoDeviceInfo, DeviceManager, and DeviceProfile, which provide detailed control over camera devices and other hardware. These features allow for greater flexibility in managing devices, including support for various types of cameras, provided the necessary permissions are granted.
 
The UI Library (Composite), on the other hand, is designed as a turnkey solution to simplify integration and provide out-of-the-box support for common use cases. As such, it is more opinionated and doesn't expose the same level of flexibility as the native Calling SDK. This design decision prioritizes ease of use and rapid development but may limit the ability to fully customize or extend support for non-standard hardware.
 
That said, it is possible to fork the UI Library and customize it to incorporate additional functionality from the native Calling SDK. For example, preliminary Android TV support has demonstrated that USB webcams can be utilized with some modifications. However, making the UI Library fully generic for diverse camera devices introduces challenges, such as handling inconsistent or user-unfriendly camera enumeration, which can degrade the overall user experience.
 
We recommend reaching out to our product team via [this feedback form](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR5RYBnUcHHJEqeMSyRZjK0JUNkVCRlAyS0lHR005RTJLME9CWklNNzEzUC4u) to request the addition of the features you need. This helps us better understand your requirements and evaluate the feasibility of exposing these capabilities in a future release.
